In [1]:
%pip install mlxtend

Requirement already satisfied: mlxtend in /opt/anaconda3/lib/python3.14/site-packages (0.25.0)
Requirement already satisfied: scipy>=1.16.3 in /opt/anaconda3/lib/python3.14/site-packages (from mlxtend) (1.18.0)
Requirement already satisfied: numpy>=2.3.5 in /opt/anaconda3/lib/python3.14/site-packages (from mlxtend) (2.4.6)
Requirement already satisfied: pandas>=2.3.3 in /opt/anaconda3/lib/python3.14/site-packages (from mlxtend) (3.0.3)
Requirement already satisfied: scikit-learn>=1.8.0 in /opt/anaconda3/lib/python3.14/site-packages (from mlxtend) (1.9.0)
Requirement already satisfied: matplotlib>=3.10.8 in /opt/anaconda3/lib/python3.14/site-packages (from mlxtend) (3.11.0)
Requirement already satisfied: joblib>=1.5.2 in /opt/anaconda3/lib/python3.14/site-packages (from mlxtend) (1.5.3)
Requirement already satisfied: contourpy>=1.0.1 in /opt/anaconda3/lib/python3.14/site-packages (from matplotlib>=3.10.8->mlxtend) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /opt/anaconda3/lib/python3.14/site-packages (from matplotlib>=3.10.8->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /opt/anaconda3/lib/python3.14/site-packages (from matplotlib>=3.10.8->mlxtend) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/anaconda3/lib/python3.14/site-packages (from matplotlib>=3.10.8->mlxtend) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /opt/anaconda3/lib/python3.14/site-packages (from matplotlib>=3.10.8->mlxtend) (26.0)
Requirement already satisfied: pillow>=9 in /opt/anaconda3/lib/python3.14/site-packages (from matplotlib>=3.10.8->mlxtend) (12.3.0)
Requirement already satisfied: pyparsing>=3 in /opt/anaconda3/lib/python3.14/site-packages (from matplotlib>=3.10.8->mlxtend) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in /opt/anaconda3/lib/python3.14/site-packages (from matplotlib>=3.10.8->mlxtend) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.14/site-packages (from python-dateutil>=2.7->matplotlib>=3.10.8->mlxtend) (1.17.0)
Requirement already satisfied: narwhals>=2.0.1 in /opt/anaconda3/lib/python3.14/site-packages (from scikit-learn>=1.8.0->mlxtend) (2.23.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in /opt/anaconda3/lib/python3.14/site-packages (from scikit-learn>=1.8.0->mlxtend) (3.5.0)
Note: you may need to restart the kernel to use updated packages.

# 1. Business understanding

In [2]:
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('drone_prod_groups.csv')

df

,ID,Prod1,Prod2,Prod3,Prod4,Prod5,Prod6,Prod7,Prod8,Prod9,...,Prod11,Prod12,Prod13,Prod14,Prod15,Prod16,Prod17,Prod18,Prod19,Prod20
0,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,1,0,0,0,0,1
1,2,0,1,0,0,0,0,0,0,1,...,0,0,0,0,1,1,1,1,1,1
2,3,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,1
3,4,1,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,1
4,5,0,0,0,0,0,0,0,0,1,...,0,0,0,0,1,0,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,99996,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
99996,99997,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
99997,99998,0,1,0,0,0,0,0,0,1,...,0,0,0,0,1,0,0,1,0,0
99998,99999,0,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,1
99999,100000,0,0,0,0,1,0,0,0,0,...,0,1,0,1,0,0,0,0,0,0

In [4]:
print('Dataframes sum of NA values:')
print(df.isna().sum())
print('All NA values: ', df.isna().sum().sum())
print('\nDataframe dataypes:')
print(df.dtypes)

Dataframes sum of NA values:
ID         0
Prod1      0
 Prod2     0
 Prod3     0
 Prod4     0
 Prod5     0
 Prod6     0
 Prod7     0
 Prod8     0
 Prod9     0
 Prod10    0
 Prod11    0
 Prod12    0
 Prod13    0
 Prod14    0
 Prod15    0
 Prod16    0
 Prod17    0
 Prod18    0
 Prod19    0
 Prod20    0
dtype: int64
All NA values:  0

Dataframe dataypes:
ID         int64
Prod1      int64
 Prod2     int64
 Prod3     int64
 Prod4     int64
 Prod5     int64
 Prod6     int64
 Prod7     int64
 Prod8     int64
 Prod9     int64
 Prod10    int64
 Prod11    int64
 Prod12    int64
 Prod13    int64
 Prod14    int64
 Prod15    int64
 Prod16    int64
 Prod17    int64
 Prod18    int64
 Prod19    int64
 Prod20    int64
dtype: object

In [5]:
df = df.drop(columns='ID')

df = df.astype(bool)

In [6]:
frequent_itemsets = apriori(df, min_support=0.1, use_colnames=True)
frequent_itemsets

    support                       itemsets
0   0.10998             frozenset({Prod1})
1   0.13098            frozenset({ Prod2})
2   0.10459            frozenset({ Prod5})
3   0.13499            frozenset({ Prod7})
4   0.16179            frozenset({ Prod8})
5   0.19853            frozenset({ Prod9})
6   0.10848           frozenset({ Prod11})
7   0.15971           frozenset({ Prod12})
8   0.14557           frozenset({ Prod14})
9   0.11880           frozenset({ Prod15})
10  0.13100           frozenset({ Prod16})
11  0.12166           frozenset({ Prod18})
12  0.20626           frozenset({ Prod19})
13  0.14798           frozenset({ Prod20})
14  0.11145   frozenset({ Prod9,  Prod15})
15  0.13476  frozenset({ Prod20,  Prod19})

In [7]:
rules_conf = association_rules(frequent_itemsets, metric='confidence', min_threshold=0.5)
rules_supp = association_rules(frequent_itemsets, metric='support', min_threshold=0.1)
rules_lift = association_rules(frequent_itemsets, metric='lift', min_threshold=4)

rules_conf = rules_conf.sort_values(by='confidence', ascending=False)
rules_supp = rules_supp.sort_values(by='support', ascending=False)
rules_lift = rules_lift.sort_values(by='lift', ascending=False)

In [8]:
rules_conf

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
1,frozenset({ Prod15}),frozenset({ Prod9}),0.11880,0.19853,0.11145,0.938131,4.725388,1.0,0.087865,12.954372,0.894663,0.541335,0.922806,0.749754
2,frozenset({ Prod20}),frozenset({ Prod19}),0.14798,0.20626,0.13476,0.910664,4.415125,1.0,0.104238,8.884845,0.907849,0.613997,0.887449,0.782007
3,frozenset({ Prod19}),frozenset({ Prod20}),0.20626,0.14798,0.13476,0.653350,4.415125,1.0,0.104238,2.457869,0.974508,0.613997,0.593144,0.782007
0,frozenset({ Prod9}),frozenset({ Prod15}),0.19853,0.11880,0.11145,0.561376,4.725388,1.0,0.087865,2.009011,0.983664,0.541335,0.502243,0.749754

In [9]:
rules_supp

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
2,frozenset({ Prod20}),frozenset({ Prod19}),0.14798,0.20626,0.13476,0.910664,4.415125,1.0,0.104238,8.884845,0.907849,0.613997,0.887449,0.782007
3,frozenset({ Prod19}),frozenset({ Prod20}),0.20626,0.14798,0.13476,0.653350,4.415125,1.0,0.104238,2.457869,0.974508,0.613997,0.593144,0.782007
0,frozenset({ Prod9}),frozenset({ Prod15}),0.19853,0.11880,0.11145,0.561376,4.725388,1.0,0.087865,2.009011,0.983664,0.541335,0.502243,0.749754
1,frozenset({ Prod15}),frozenset({ Prod9}),0.11880,0.19853,0.11145,0.938131,4.725388,1.0,0.087865,12.954372,0.894663,0.541335,0.922806,0.749754

In [10]:
rules_lift

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,frozenset({ Prod9}),frozenset({ Prod15}),0.19853,0.11880,0.11145,0.561376,4.725388,1.0,0.087865,2.009011,0.983664,0.541335,0.502243,0.749754
1,frozenset({ Prod15}),frozenset({ Prod9}),0.11880,0.19853,0.11145,0.938131,4.725388,1.0,0.087865,12.954372,0.894663,0.541335,0.922806,0.749754
2,frozenset({ Prod20}),frozenset({ Prod19}),0.14798,0.20626,0.13476,0.910664,4.415125,1.0,0.104238,8.884845,0.907849,0.613997,0.887449,0.782007
3,frozenset({ Prod19}),frozenset({ Prod20}),0.20626,0.14798,0.13476,0.653350,4.415125,1.0,0.104238,2.457869,0.974508,0.613997,0.593144,0.782007